name: Build
on:
  push:
    branches:
      - master
      - ystinia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set artifact name
        id: vars
        run: |
          if [ "${{ github.ref_name }}" = "master" ]; then
            echo "name=Decoder" >> $GITHUB_OUTPUT
          else
            echo "name=Decoder-NG" >> $GITHUB_OUTPUT
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build
        env:
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEY_ALIAS:     ${{ secrets.KEY_ALIAS }}
          KEY_PASS:      ${{ secrets.KEY_PASS }}
        run: |
          echo "${{ secrets.KEY }}" | base64 -d > key.jks
          ./gradlew bundleRelease
          mv app/build/outputs/bundle/release/app-release.aab ${{ steps.vars.outputs.name }}.aab
          ./gradlew assembleRelease
          mv app/build/outputs/apk/release/app-release.apk ${{ steps.vars.outputs.name }}.apk

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            ${{ steps.vars.outputs.name }}.aab
            ${{ steps.vars.outputs.name }}.apk
